[package]
name = "retry-rs"
version = "0.1.0"
edition = "2021"


[dependencies]
async-trait = "0.1.86"
tokio = { version = "1.43.0", features = ["time","macros", "rt", "fs"] }
rand = "0.9.0"



[workspace]
members = [
    ".",
    "src/retry-rs-macros",
    "examples/sqlx_sqlite_example",
    "tests"
]


[workspace.dependencies]
retry-rs = {path = "."}
retry-rs-macros = {path = "src/retry-rs-macros"}
