[package]
name = "retriers_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.86"
tokio = { version = "1.43.0", features = ["time", "macros", "rt", "fs"] }
rand = "0.9.0"


[dev-dependencies]
retriers_macro = {path = "../retriers_macro" }