[package]
name = "fs_example"
version = "0.1.0"
edition = "2024"

[dependencies]
retry-rs = { workspace = true, features = ["macros"] }
tokio = { version = "1.43.0", features = ["full"] }
nix = { version = "0.29.0", features = ["fs"] }
fs2 = "0.4.3"
log = "0.4.26"
env_logger = "0.11.6"
