[package]
name = "fs_example"
version = "0.0.1"
edition = "2024"

[dependencies]
eztry = { workspace = true, features = ["macros"] }
tokio = { version = "1.43.0", features = ["full"] }
fs2 = "0.4.3"
log = "0.4.26"
env_logger = "0.11.6"
