
name: Test

# This workflow run tests and build for each push

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          
          
      # ./test is a script that runs tests with the correct args, rather than trying to maintain a long command here          
      - name: Run tests
        run: |
          ./test